//! `existence audit --mirrors` — surfaces that copy the ontology and then rot.
//!
//! Mirrors are declared in `existence.toml`:
//!
//! ```toml
//! [[mirrors]]
//! path = "../philosophy/src"   # node-per-file copy: lay definitions compared per term
//! kind = "nodes"
//! optional = true              # skip silently when the path is absent (another machine)
//!
//! [[mirrors]]
//! path = "terms.md"            # generated by `existence toc`; --fix regenerates it
//! kind = "toc"
//!
//! [[mirrors]]
//! path = "~/.claude/CLAUDE.md" # a `| **Term** | summary |` table
//! kind = "table"
//! optional = true
//! compare = "paraphrase"       # default; "wording" also scores row vs node text
//! ```
//!
//! `nodes` mirrors are reported as a per-term diff of lay definitions with
//! the markdown flattened to prose, so a `"broader"` link title, a link
//! target spelling, or a missing Axiology section is not drift. `toc` mirrors are regenerated and
//! compared byte for byte; `--fix` rewrites them. `table` mirrors are report
//! only, and what counts as drift depends on `compare`. A one-line summary
//! table is a paraphrase by nature — a good summary deliberately picks
//! shorter, different words, so word overlap measures style, not accuracy
//! (`Focus`: "Selectively concentrating on one system of the Existence" vs
//! "Finite attention applied to a scope" share no words and say the same
//! thing). So `paraphrase`, the default, reports only a row whose term has no
//! node, which is the failure that silently rots a mirror when a term is
//! renamed or removed. `compare = "wording"` additionally scores each row
//! against its node's lay definition and lists both texts below
//! [`TABLE_THRESHOLD`]; choose it for a table meant to quote the ontology.

use crate::commands::audit::Finding;
use crate::commands::toc;
use crate::config::{self, Config, Mirror};
use crate::markdown;
use regex::Regex;
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

/// Below this word-overlap (Jaccard) a table row is reported as drifted.
pub const TABLE_THRESHOLD: f64 = 0.25;

/// Check every declared mirror; regenerate `toc` mirrors when `fix` is set.
pub fn check(ontology_dir: &Path, config: &Config, fix: bool) -> Result<Vec<Finding>, String> {
    let mut out = Vec::new();
    for mirror in &config.mirrors {
        // A typo here would silently disable the wording check, so fail loudly.
        if !matches!(mirror.compare.as_str(), "paraphrase" | "wording") {
            return Err(format!(
                "mirror {}: unknown compare '{}' (expected paraphrase or wording)",
                mirror.path, mirror.compare
            ));
        }
        let path = resolve(ontology_dir, &mirror.path)?;
        // A generated index that does not exist yet is stale, not missing:
        // `--fix` creates it.
        if !path.exists() && mirror.kind != "toc" {
            if !mirror.optional {
                out.push(finding(
                    "mirror_missing",
                    "error",
                    &mirror.path,
                    format!("mirror {} ({}) does not exist", mirror.path, mirror.kind),
                    None,
                ));
            }
            continue;
        }
        match mirror.kind.as_str() {
            "nodes" => out.extend(nodes_mirror(ontology_dir, mirror, &path)?),
            "toc" => out.extend(toc_mirror(ontology_dir, mirror, &path, fix)?),
            "table" => out.extend(table_mirror(ontology_dir, mirror, &path)?),
            other => {
                return Err(format!(
                    "mirror {}: unknown kind '{other}' (expected nodes, toc, or table)",
                    mirror.path
                ));
            }
        }
    }
    Ok(out)
}

/// `~/x` against the home directory, relative paths against the ontology.
pub fn resolve(ontology_dir: &Path, path: &str) -> Result<PathBuf, String> {
    if let Some(rest) = path.strip_prefix("~/") {
        return Ok(config::home_dir()?.join(rest));
    }
    let p = Path::new(path);
    Ok(if p.is_absolute() {
        p.to_path_buf()
    } else {
        ontology_dir.join(p)
    })
}

fn finding(
    check: &str,
    severity: &str,
    term: &str,
    message: String,
    fix: Option<String>,
) -> Finding {
    Finding {
        class: "mirrors".into(),
        check: check.into(),
        severity: severity.into(),
        term: term.into(),
        message,
        fix,
        fixed: false,
    }
}

/// Per-term lay-definition diff between the ontology and a node-per-file copy.
fn nodes_mirror(ontology_dir: &Path, mirror: &Mirror, dir: &Path) -> Result<Vec<Finding>, String> {
    let src_dir = ontology_dir.join("src");
    let mut out = Vec::new();
    for term in markdown::list_terms(&src_dir)? {
        let theirs = dir.join(format!("{term}.md"));
        if !theirs.is_file() {
            continue;
        }
        let ours = read(&src_dir.join(format!("{term}.md")))?;
        let theirs = read(&theirs)?;
        let a = markdown::extract_definition(&ours);
        let b = markdown::extract_definition(&theirs);
        match (a, b) {
            (Some(a), Some(b)) => {
                if comparable(&a) != comparable(&b) {
                    out.push(finding(
                        "mirror_drift",
                        "warning",
                        &term,
                        format!(
                            "lay definition differs from mirror {}\n  ontology: {}\n  mirror:   {}",
                            mirror.path,
                            markdown::plain_text(&a),
                            markdown::plain_text(&b)
                        ),
                        None,
                    ));
                }
            }
            (Some(_), None) => out.push(finding(
                "mirror_drift",
                "warning",
                &term,
                format!(
                    "mirror {} has no lay definition for this term (no Ontology section)",
                    mirror.path
                ),
                None,
            )),
            (None, _) => {}
        }
    }
    Ok(out)
}

/// The comparison key for a lay definition: the prose with links flattened
/// to their text and whitespace collapsed. Link titles and targets are
/// structure (`"broader"`, a `.md` suffix), not wording, so they do not
/// count as drift.
pub fn comparable(definition: &str) -> String {
    markdown::plain_text(definition)
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

/// A generated index: compare with `existence toc` output, rewrite on `--fix`.
fn toc_mirror(
    ontology_dir: &Path,
    mirror: &Mirror,
    file: &Path,
    fix: bool,
) -> Result<Vec<Finding>, String> {
    let base = toc::default_base(ontology_dir, Some(file));
    let expected = toc::to_markdown(&toc::build(ontology_dir, None, &base)?);
    let current = if file.is_file() {
        read(file)?
    } else {
        String::new()
    };
    if current == expected {
        return Ok(Vec::new());
    }
    let mut f = finding(
        "mirror_stale",
        "error",
        &mirror.path,
        if file.is_file() {
            format!("{} no longer matches `existence toc` output", mirror.path)
        } else {
            format!("{} does not exist yet", mirror.path)
        },
        Some(format!(
            "regenerate with `existence toc -o {}`",
            mirror.path
        )),
    );
    if fix {
        std::fs::write(file, expected)
            .map_err(|e| format!("Failed to write {}: {e}", file.display()))?;
        f.fixed = true;
    }
    Ok(vec![f])
}

/// A `| **Term** | summary |` table: rows without a node, and — only when
/// `compare = "wording"` — rows whose summary shares too few words with the
/// node's lay definition. See the module docs for why wording is opt-in.
fn table_mirror(ontology_dir: &Path, mirror: &Mirror, file: &Path) -> Result<Vec<Finding>, String> {
    let src_dir = ontology_dir.join("src");
    let row = Regex::new(r"^\|\s*\*\*([^*|]+)\*\*\s*\|\s*(.*?)\s*\|\s*$").unwrap();
    let mut out = Vec::new();
    for line in read(file)?.lines() {
        let Some(cap) = row.captures(line) else {
            continue;
        };
        let title = cap[1].trim();
        let summary = cap[2].trim();
        let term = title.to_lowercase().replace(' ', "-");
        let node = src_dir.join(format!("{term}.md"));
        if !node.is_file() {
            out.push(finding(
                "mirror_drift",
                "warning",
                &term,
                format!(
                    "table row **{title}** in {} has no node src/{term}.md",
                    mirror.path
                ),
                None,
            ));
            continue;
        }
        if mirror.compare != "wording" {
            continue;
        }
        let Some(definition) = markdown::extract_definition(&read(&node)?) else {
            continue;
        };
        let definition = markdown::plain_text(&definition);
        let score = jaccard(&definition, summary);
        if score < TABLE_THRESHOLD {
            out.push(finding(
                "mirror_drift",
                "warning",
                &term,
                format!(
                    "table row **{title}** in {} shares few words with the node's lay definition (overlap {score:.2})\n  node:  {definition}\n  table: {summary}",
                    mirror.path
                ),
                None,
            ));
        }
    }
    Ok(out)
}

fn words(text: &str) -> BTreeSet<String> {
    text.to_lowercase()
        .split(|c: char| !c.is_alphanumeric())
        .filter(|w| w.len() >= 3)
        .map(str::to_string)
        .collect()
}

fn jaccard(a: &str, b: &str) -> f64 {
    let (a, b) = (words(a), words(b));
    let union = a.union(&b).count();
    if union == 0 {
        return 1.0;
    }
    a.intersection(&b).count() as f64 / union as f64
}

fn read(path: &Path) -> Result<String, String> {
    std::fs::read_to_string(path).map_err(|e| format!("Failed to read {}: {e}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn node(title: &str, ontology: &str) -> String {
        format!(
            "# {title}\n\n## Ontology\n\n{ontology}\n\n## Axiology\n\nx\n\n## Epistemology\n\ny\n"
        )
    }

    fn setup(tmp: &Path) -> (PathBuf, Config) {
        let onto = tmp.join("onto");
        let src = onto.join("src");
        fs::create_dir_all(&src).unwrap();
        fs::write(
            src.join("entity.md"),
            node(
                "Entity",
                "Anything in [Existence](./existence.md \"broader\") that can be distinguished.",
            ),
        )
        .unwrap();
        fs::write(
            src.join("scope.md"),
            node(
                "Scope",
                "The reach of an [Entity](./entity.md); a [domain](./domain.md \"broader\").",
            ),
        )
        .unwrap();
        fs::write(
            src.join("state.md"),
            node("State", "The condition of an [Entity](./entity.md)."),
        )
        .unwrap();
        fs::write(
            src.join("existence.md"),
            node("Existence", "Everything that is."),
        )
        .unwrap();
        fs::write(src.join("domain.md"), node("Domain", "A bounded system.")).unwrap();
        // Mirror: identical after title strip, drifted, missing Ontology heading.
        let mirror = tmp.join("philosophy/src");
        fs::create_dir_all(&mirror).unwrap();
        fs::write(
            mirror.join("entity.md"),
            node(
                "Entity",
                "Anything in [Existence](./existence.md) that can be distinguished.",
            ),
        )
        .unwrap();
        fs::write(
            mirror.join("scope.md"),
            node("Scope", "The reach of a [perspective](./perspective.md)."),
        )
        .unwrap();
        fs::write(
            mirror.join("state.md"),
            "# State\n\n## Axiology\n\nThe condition of an entity.\n",
        )
        .unwrap();
        // Table: a close row, a drifted row, a row with no node.
        fs::write(
            tmp.join("TABLE.md"),
            "| Term | Definition |\n|---|---|\n| **Entity** | Anything in Existence that can be distinguished from anything else |\n| **Scope** | Breadth/depth/reach of a perspective; bounds what's relevant |\n| **Ghost** | Not a node |\n",
        )
        .unwrap();
        let toml = format!(
            "[meta]\nname = \"t\"\ndescription = \"d\"\n\n[rings.0]\nname = \"k\"\ndescription = \"c\"\nterms = [\"existence\", \"entity\", \"scope\", \"state\", \"domain\"]\n\n[[mirrors]]\npath = \"../philosophy/src\"\nkind = \"nodes\"\n\n[[mirrors]]\npath = \"terms.md\"\nkind = \"toc\"\n\n[[mirrors]]\npath = \"{}\"\nkind = \"table\"\ncompare = \"wording\"\n\n[[mirrors]]\npath = \"../nowhere\"\nkind = \"nodes\"\noptional = true\n\n[[mirrors]]\npath = \"../also-nowhere\"\nkind = \"nodes\"\n",
            tmp.join("TABLE.md").display()
        );
        fs::write(onto.join("existence.toml"), toml).unwrap();
        let config = Config::load(&onto.join("existence.toml")).unwrap();
        (onto, config)
    }

    /// Rewrite the fixture's table mirror to use a different `compare` value.
    fn with_compare(onto: &Path, value: &str) -> Config {
        let toml_path = onto.join("existence.toml");
        let toml = fs::read_to_string(&toml_path)
            .unwrap()
            .replace("compare = \"wording\"", &format!("compare = \"{value}\""));
        fs::write(&toml_path, toml).unwrap();
        Config::load(&toml_path).unwrap()
    }

    #[test]
    fn a_paraphrase_table_reports_a_missing_node_but_not_different_wording() {
        let tmp = tempfile::tempdir().unwrap();
        let (onto, _) = setup(tmp.path());
        // `paraphrase` is the default, so dropping the key must behave the same
        // as setting it; check both spellings reach the same findings.
        for toml_value in ["paraphrase", ""] {
            let config = if toml_value.is_empty() {
                let toml_path = onto.join("existence.toml");
                let toml = fs::read_to_string(&toml_path)
                    .unwrap()
                    .replace("compare = \"paraphrase\"\n", "");
                fs::write(&toml_path, toml).unwrap();
                Config::load(&toml_path).unwrap()
            } else {
                with_compare(&onto, toml_value)
            };
            let table: Vec<Finding> = check(&onto, &config, false)
                .unwrap()
                .into_iter()
                .filter(|f| f.message.contains("TABLE.md"))
                .collect();
            // `Scope`'s row says the same thing in its own words (overlap < 0.25
            // under `wording`); only the row with no node survives.
            assert_eq!(table.len(), 1, "{table:#?} for compare={toml_value:?}");
            assert_eq!(table[0].term, "ghost");
            assert!(table[0].message.contains("has no node"));
        }
    }

    #[test]
    fn an_unknown_compare_value_is_a_config_error() {
        let tmp = tempfile::tempdir().unwrap();
        let (onto, _) = setup(tmp.path());
        let config = with_compare(&onto, "exact");
        let err = check(&onto, &config, false).unwrap_err();
        assert!(
            err.contains("unknown compare 'exact'") && err.contains("paraphrase or wording"),
            "{err}"
        );
    }

    #[test]
    fn nodes_toc_table_and_missing_mirrors_are_reported() {
        let tmp = tempfile::tempdir().unwrap();
        let (onto, config) = setup(tmp.path());
        let findings = check(&onto, &config, false).unwrap();
        let keys: Vec<(&str, &str, &str)> = findings
            .iter()
            .map(|f| (f.check.as_str(), f.term.as_str(), f.severity.as_str()))
            .collect();
        assert_eq!(
            keys,
            [
                ("mirror_drift", "scope", "warning"),
                ("mirror_drift", "state", "warning"),
                ("mirror_stale", "terms.md", "error"),
                ("mirror_drift", "scope", "warning"),
                ("mirror_drift", "ghost", "warning"),
                ("mirror_missing", "../also-nowhere", "error"),
            ],
            "{findings:#?}"
        );
        assert_eq!(
            findings[0].message,
            "lay definition differs from mirror ../philosophy/src\n  ontology: The reach of an Entity; a domain.\n  mirror:   The reach of a perspective."
        );
        assert!(findings[1].message.contains("no Ontology section"));
        assert_eq!(findings[2].message, "terms.md does not exist yet");
        assert_eq!(
            findings[2].fix.as_deref(),
            Some("regenerate with `existence toc -o terms.md`")
        );
        assert!(!findings[2].fixed);
        assert!(findings[3].message.contains("overlap 0."));
        assert!(
            findings[3]
                .message
                .contains("table: Breadth/depth/reach of a perspective")
        );
        assert!(findings[4].message.contains("has no node src/ghost.md"));
    }

    #[test]
    fn fix_regenerates_the_toc_mirror_and_a_second_pass_is_quiet() {
        let tmp = tempfile::tempdir().unwrap();
        let (onto, config) = setup(tmp.path());
        let findings = check(&onto, &config, true).unwrap();
        let stale: Vec<&Finding> = findings
            .iter()
            .filter(|f| f.check == "mirror_stale")
            .collect();
        assert!(stale[0].fixed);
        let terms = fs::read_to_string(onto.join("terms.md")).unwrap();
        assert!(terms.contains("[**Entity**](src/entity.md)"), "{terms}");
        let again = check(&onto, &config, false).unwrap();
        assert!(
            !again.iter().any(|f| f.check == "mirror_stale"),
            "{again:#?}"
        );
        // Editing a node makes it stale again.
        fs::write(
            onto.join("src/domain.md"),
            node("Domain", "A bounded system of interest."),
        )
        .unwrap();
        let third = check(&onto, &config, false).unwrap();
        let stale: Vec<&Finding> = third.iter().filter(|f| f.check == "mirror_stale").collect();
        assert_eq!(
            stale[0].message,
            "terms.md no longer matches `existence toc` output"
        );
    }

    #[test]
    fn comparable_strips_titles_and_whitespace_only() {
        assert_eq!(
            comparable("A [b](./b.md \"broader\")   c\n d"),
            comparable("A [b](./b.md) c d")
        );
        assert_eq!(
            comparable("[env](./environment.md)"),
            comparable("[env](./environment)")
        );
        assert_ne!(comparable("A [b](./b.md)"), comparable("A [c](./c.md)"));
    }

    #[test]
    fn resolve_handles_home_relative_and_absolute() {
        let onto = Path::new("/o");
        assert_eq!(
            resolve(onto, "terms.md").unwrap(),
            PathBuf::from("/o/terms.md")
        );
        assert_eq!(resolve(onto, "/abs/x").unwrap(), PathBuf::from("/abs/x"));
        let home = resolve(onto, "~/.claude/CLAUDE.md").unwrap();
        assert!(home.is_absolute() && home.ends_with(".claude/CLAUDE.md"));
    }
}
